# Generated by Django 3.2.25 on 2024-06-09 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at', 'updated_at'], 'verbose_name': 'Komentář', 'verbose_name_plural': 'Komentáře'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_at', 'updated_at', 'title'], 'verbose_name': 'Příspěvek', 'verbose_name_plural': 'Příspěvky'},
        ),
    ]
